version: '3.7'

services:
  clash:
    image: oopsfoo/clashdock
    # build: .
    restart: always
    ports:
      - "9090:9090"
      - "7890:7890"
      - "7891:7891"
    # network_mode: "host"
    volumes:
      - "./conf:/clash/conf"
    container_name: clashdock
